# Generated by Django 6.0 on 2025-12-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempModel',
        ),
    ]
